### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.message'

### ISSUE THREAD

**Issue by Xero999999** [clearkimura/Customizer#220]
Hi, When I try to open Customizer, I get the following error: 

/usr/sbin/customizer-gui:281: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if QT_VER is not 5:
/usr/sbin/customizer-gui:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import sys, os, atexit, subprocess, imp
Traceback (most recent call last):
  File "/usr/sbin/customizer-gui", line 29, in <module>
    import lib.config as config
ModuleNotFoundError: No module named 'lib.config'

The Customizer CLI displays the following:

Traceback (most recent call last):
  File "/usr/sbin/customizer", line 11, in <module>
    import lib.message as message
ModuleNotFoundError: No module named 'lib.message'

I am trying to use your tool, it is the best I have found :)

**Comment by kamilion** [comment]
Uhh, what host system distro and version is this from? I'll install it in a VM and check it out.

**Comment by Xero999999** [comment]
I use kubuntu

**Comment by Xero999999** [comment]
Kubuntu 21.04

**Comment by kamilion** [comment]
Thanks, I'll go check it out when I've got some time to spare this holiday season, and see if I can make sure it'll work with 22.04 LTS.
